import Head from "next/head";
// import Image from 'next/image'
import { Footer } from "src/compornents/Footer";
import { Header } from "src/compornents/Header";
import { Main } from "src/compornents/Main";
import styles from "src/styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>インターバルタイマー</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />
      
      <Main />

      <Footer />
    </div>
  );
}
