import Head from "next/head";
// import Image from 'next/image'
import { Footer } from "../compornents/Footer";
import Headline from "../compornents/Headline";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Headline />
      </main>

      <Footer />
    </div>
  );
}
